#!/bin/sh

set -e

BUILD_DIR=/tmp/build/foo-java

# Check if push occur in master branch
read oldrev newrev refname
branch=$(git rev-parse --symbolic --abbrev-ref $refname)
if [ "$branch" != "master" ]; then
    echo "No commit to master. Deploying nothing."
    exit 1
fi

# Check the remote git repository whetherit is bare
IS_BARE=$(git rev-parse --is-bare-repository)
echo "checking source repo bare." 
if [ -z "$IS_BARE" ]; then
    echo "post-receive: fatal: this repo is not bare. Exit." 
    exit 1
fi

# Get the latest commit subject to chek if [deploy] is marked
SUBJECT=$(git log -1 --pretty=format:"%s")
echo "checking commit info: $SUBJECT" 
IS_DEPLOY=$(echo "$SUBJECT" | grep "\[deploy\]")

echo $IS_DEPLOY
if [ -z "$IS_DEPLOY" ]; then
   echo "post-receive: info: Not Deploy. Exit." 
   exit 1
fi

echo "Auto deployment activated." 

if [ ! -d $BUILD_DIR ] ; then
   echo "post-receive: fatal: Build directory does not exist:\"$BUILD_DIR\"" 
   exit 1
fi

# Prepare build env

# Build
unset GIT_DIR

echo "go into $BUILD_DIR"
cd $BUILD_DIR

echo "git reset --hard"
git reset --hard

echo "git pull origin master"
git pull origin master

echo "mvn deploy"
mvn tomcat7:deploy
